# Generated by Django 2.2 on 2021-08-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration_app', '0002_auto_20210812_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_registration_app.User')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_written', to='dojo_reads_app.Author')),
                ('reviewed_by', models.ManyToManyField(related_name='books_reviewed', to='login_registration_app.User')),
            ],
        ),
    ]
