# Generated by Django 2.2 on 2021-08-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0003_auto_20210821_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
    ]
